.eslintrc.json, Components/MyPage/SwitchButton.tsx
- 마이페이지에서 성별을 고르는 버튼을 구현하였습니다.
- 각 버튼을 누르면 해당 옵션이 활성화됩니다.
- feat/SwitchButton -> dev
-SwitchButton 컴포넌트 구현
by @nno3onn
=> feat(SwitchButton): MyPage의 SwitchButton 컴포넌트 구현

Components/MyPage/PositionTag.tsx
- 마이페이지 포지션 태그를 구현하였습니다.
- 비활성화인 버튼을 누르면 활성화, 활성화 버튼을 누르면 비활성홯됩니다.
- feat/PositionTag -> dev
- PositionTag 컴포넌트 구현
by @nno3onn
=> feat(PositionTag): MyPage의 PositionTag 컴포넌트 구현

Components/MyPage/ProfileContainer.tsx
- 마이페이지의 프로필 컨테이너 컴포넌트를 구현하였습니다.
- feat/ProfileContainer -> dev
- ProfileContainer 컴포넌트 구현
by @nno3onn
=> feat(ProfileContainer): MyPage의 ProfileContainer 컴포넌트 구현

Components/Common/Toggle.tsx
- toggle 컴포넌트를 구현
- Props로 기본값 설정이 기능합니다.
- Todo 문서화로 나중에 브랜드 컬러가 지정되면 변경할 부분도 문서추가합니다.
- feat/toggle -> dev
- 많은 기능은 없습니다.
(#8 ) by @arch-spatula
=> feat (Toggle): Toggle 컴포넌트 구현

Components/Common/DropDown.tsx
- 불친절한 드롭다운 리펙토링
- 추후 스타일링 필요
#8
- 친절한 드롭다운으로 리펙토링
- feat/DropDown -> dev
- 사용할 컴포넌트, 페이지에서 data="(ex: 회원가입)" 작성시 셀렉트 자동 완성로직 구현
(#8) by @hyoloui
=> refactor: DropDown.tsx

Components/Detail/Comment.tsx, Components/Detail/CommentInput.tsx, Components/Detail/CommentItem.tsx, Components/Detail/CommentList.tsx
- 댓글 CRUD UI 구성 했습니다. 기능 부분은 포함되어 있지 않습니다. 
- feat/ -> dev
- 초기 UI 커밋입니다. 
#9  by @yunjunhojj
=> feat: 댓글 CRUD UI 구성

Components/Post/Post.tsx, pages/create-post.tsx
- text editor width 수정
- 아래 여백 추가
- fix/#75 -> dev
- styled component 수정
(#75) by @hyoloui
=> fix(Post, create-post): text editor width 수정

Components/Detail/DetailHeader.tsx
- 디테일 페이지의 좋아요 기능 구현
- feat/Like -> dev
- 디테일 페이지의 좋아요 기능을 구현하였습니다. 처음 페이지를 불러올 때에만 like 여부를 불러오면 될 것 같아서 react-query는 사용하지 않았습니다.
#67  by @nno3onn
=> feat(Like): 좋아요 기능 구현

Components/Detail/DetailHeader.tsx
- 디테일 페이지의 북마크 기능을 구현하였습니다.
- feat/Bookmark -> dev
- 좋아요와 동일하게 구현하였습니다.
(이슈 번호를 여기 입력 해 주세요.) by @
=> feat(Bookmark): 디테일 페이지 북마크 기능 구현

Components/Common/index.ts, Components/MyPage/EditProfileContainer.tsx, Components/MyPage/index.ts, lib/recoil/index.ts, lib/recoil/myPageAtoms.ts, pages/profile/[[...userId]].tsx, types.d.ts
- import 정리
- input의 type을 number로 수정
- 전화번호 유효성 검사하고 helper text로 피드백
- feat/ -> dev
- merge conflict 날지 확인하기 위해 조기에 PR합니다.
(#64) by @arch-spatula
=> fix(TabProfile): 전화번호 숫자 전용 및 유효성 검사

Components/MyPage/UserInfoContainer.tsx
- 로그아웃 완료시 홈 화면 이동
- feat/Logout -> dev
- UserInfoContainer.tsx 에서 작업
(#60 ) by @hyoloui
=> feat(UserInfoContainer): 로그아웃 기능

Components/Detail/CommentInput.tsx, Components/Detail/CommentItem.tsx, Components/Detail/CommentList.tsx
- comment 의 input 들 레이아웃 확인 했습니다. 
- feat/comment -> dev
- 댓글 입력창 위치 조절
- 댓글 수정 시 입력창 크기 조절
- 버튼 로직 추가 
(#70 .) by @yunjunhojj
=> comment 의 input 들 레이아웃 확인 했습니다. 

Components/Detail/CommentInput.tsx, Components/Detail/CommentItem.tsx, Components/Detail/CommentList.tsx, Components/Detail/DetailHeader.tsx, Components/Detail/RelatedProject.tsx, Components/Main/MainSection.tsx, Components/MyPage/CardItemContainer.tsx, Components/MyPage/EditProfileContainer.tsx, Components/MyPage/ShowProfileContainer.tsx, pages/auth/login.tsx, pages/auth/signup.tsx, pages/profile/[[...userId]].tsx, types.d.ts
- vercel build 과정에서 나는 에러들을 해결합니다.
- feat/ -> dev
- type 에러 및 lint 에러를 해결했습니다.
by @Jeremy-Kr
=> hotfix: 쓰레기줍기 리팩토링 진행

Components/Detail/DetailHeader.tsx, Components/Layouts/GNB.tsx, Components/MyPage/UserInfoContainer.tsx, Components/Post/PostEditor.tsx, pages/auth/login.tsx, pages/auth/signup.tsx, pages/profile/[[...userId]].tsx
- useEffect 빈배열 임시로 채웠습니다.
- chore/#94 -> dev
- eslint.json에 구문 추가하면 될 것으로 예상했으나, hook의존에 의한 문제로 임시 해결
- 참조 링크 : https://velog.io/@rgfdds98/debuging-React-Hook-useEffect-has-a-missing-dependency-fetchMovieData.-Either-include-it-or-remove-the-dependency-array
(#94) by @hyoloui
=> fix: useEffect dependency Array : warring

Components/Detail/RelatedProject.tsx, Components/Detail/SwiperNextButton.tsx, Components/Detail/SwiperPrevButton.tsx
- 스와이퍼 버튼이 동작하지 않던 문제를 해결합니다
- fix/swiper-button -> dev
- 지나치게 복잡한 코드를 단순화 시키고, swiper 내장 어트리뷰트인 navigation과 className을 사용 해 해결합니다.
- 동작 방식은, dev서버에서 동작하던 방식과 동일합니다.
#104  by @Jeremy-Kr
=> fix: 배포버전의 스와이퍼 버튼이 동작하지 않는 문제 해결

pages/_document.tsx, styles/global.css
- 배포시 폰트가 적용되지 않던 문제를 해결합니다.
- fix/deploy-font -> dev
- 기존 css파일에서 import 하던 폰트를 _document.tsx로 이관합니다.
#2 by @Jeremy-Kr
=> fix: 배포시 폰트가 적용되지 않던 문제를 해결합니다.

Components/MyPage/MypageTab.tsx
- width 삭제
- feat/MypageTab -> dev
- width 삭제
(#61) by @hyoloui
=> feat(MypageTab): width 수정

Components/MyPage/Banner.tsx, Components/MyPage/UserInfoContainer.tsx, lib/recoil/index.ts, lib/recoil/myPageAtoms.ts, pages/profile/[[...userId]].tsx, types.d.ts
- post 페이지 아이콘 이미지와 동일
- supabase / user-profile 로우 추가 (background_color)
- feat/MypageBG -> dev
(#110) by @hyoloui
=> feat(UserInfoContainer): 마이페이지 유져 백그라운드 기능 추가

Components/Main/MainSection.tsx, Components/Main/SideBar.tsx
- main page 카테고리별 필터 기능 추가
- feat/main-page-filtering-by-category -> dev
- 메인페이지에서 선택한 카테고리를 이용해 post를 필터링 합니다.
- 포스트 인풋과 일치를 위해 사이드바를 한글로 변경하였습니다.
- 추후 사이드바 및 포스트시 선택하는 카테고리 변경이 필요합니다.
#66 by @
=> feat: main page 카테고리별 필터 기능 추가

Components/Layouts/GNB.tsx
- feat: GNB헤더 (router 제어)
- feat/GNB -> dev
- 일단 router로 제어 했으나 추후 다른 방법 고민해보겠습니다. #90
(이슈 번호를 여기 입력 해 주세요.) by @
=> feat: GNB헤더 (router 제어)

pages/auth/signup.tsx, utils/commons/authUtils.ts
- fix: 유저프로필 디비 입력 수정 입니다
- feat/fix/signuplogic -> dev
- 얕은 지식으로 디비를 건드려서 혼란을 드렸네요 ㅠㅠ
=> fix: 유저프로필 디비 입력 수정

Components/Post/Post.tsx
- post 시 user_id 포함하도록 추가
- feat/fix/post -> dev
- 승효님 메인페이지 hover에 필요하신 것 같아서 했어요. 절대 야근한거 아닙니다 아무튼 아님 
- 추후에 리코일로 현재 로그인된 user_id 를 관리한다면, 그에 따른 리팩토링이 필요하겠습니다
이슈번호가 없을 때 했습니다... by @yunjunhojj  @hyoloui
=> feat: post 시 user_id 포함하도록 추가

Components/Common/Card/CardItem.tsx
- legacy 문법을 사용함으로써 발생하는 warning을 해결합니다.
- fix/card-image-layout-warning -> dev
- legacy 문법인 layout을 제거하고 width와 height를 추가합니다.
#141 by @Jeremy-Kr
=> fix: #141 이슈를 해결

Components/Main/LargeCategory.tsx
- 카테고리 선택 에러 해결
- fix/select-large-category-error -> dev
- 카테고리의 오른쪽 아이콘을 클릭했을 시 카테고리가 지정되지 않던 오류를 해결합니다.
#145 by @Jeremy-Kr
=> fix: 카테고리 선택 에러 해결

Components/Common/Card/CardItem.tsx
-첫 렌더링시 요청하는 테이블이 user_profile로 접근하여 글 작성하지 않은 유저에도 접근하는 오류 해결
- fix/getUserInfoError -> dev
- from("user_id) >> from("post)
(#150) by @hyoloui
=> fix(CardItem): supabase 요청 테이블 변경

Components/Post/ProjectInfoDropDown.tsx
- 개발 스택 tags 제목 width 고정시키기
- feat/ -> dev
-
(#163) by @arch-spatula
=> fix(ProjectInfoDropDown): 개발 스택 제목 width 고정

Components/Common/Skill/Skill.tsx, Components/Common/Skill/SkillList.tsx
- 스킬 태그 엔터 이벤트 추가
- 태그 유효성 검사 버그 픽스
- isComposing 관련 이슈 해결
- feat/tag-enter-event -> dev
- skill tag를 입력할 때 enter 이벤트를 추가합니다.
- skill태그의 유효성검사 관련 버그를 고치고 리팩토링을 진행합니다.
- isComposing 관련 이슈를 해결합니다.
#164 #177 #182  by @Jeremy-Kr
=> Feat/tag enter event, Fix/tag vailidation

Components/Post/ProjectInfoDropDown.tsx
- 프로젝트 기간의 start date 의 유효성 검사 추가했습니다.
- feat/dataPicker-startDate -> dev
- 프로젝트 기간의 start date 의 유효성 검사 추가했습니다. (옵션 하나 추가) 
#166 by @yunjunhojj
=> fix: 프로젝트 기간, 시작월 유효성 검사 추가해야함 #166

Components/Detail/DetailHeader.tsx
- 게시글 진입 시 북마크,좋아요 체크
- fix/like-count-and-bookmark-count -> dev
- 유져가 게시글에 진입 시 북마크와 좋아요를 눌렀었는지 체크합니다.
#170 by @Jeremy-Kr
=> fix: 게시글 진입 시 북마크,좋아요 체크

Components/Detail/Comment.tsx, Components/Detail/CommentInput.tsx, Components/Detail/CommentItem.tsx, Components/Detail/CommentList.tsx
- 댓글에 프로필 데이터가 들어가도록 수정했습니다. 
- feat/commet user name -> dev
- DB수정을 처음에 생각하였고, 말씀 드렸는데. 생각해보니 유저프로필의 사진은 항상 최신화된 사진 데이터가 필요할 것으로 보아 댓글 불러오는 곳에서 user_profile에 접근하도록 구성했습니다. 
#169  by @yunjunhojj
=> 댓글에 보여지는 유저프로필 및 유저이름 수정 

Components/Common/Tags.tsx
- tag overflow fix
- fix/tag-components-overflow -> dev
- tag가 overflow 되는 현상을 수정합니다.
#168 by @Jeremy-Kr
=> fix: tag overflow fix

styles/styled.d.ts, styles/theme.ts
- theme provider 설정
- 이제 전역에서 theme provider를 사용할 수 있습니다.
=> chore: theme provider 설정

Components/Main/DetailModal.tsx, hooks/common/index.ts, hooks/common/useStopScroll.ts
- custom hook으로 추상화할 것입니다.
- mount에 스크롤을 정지하고 unmount에 스크롤이 풀릴 것입니다.
- feat/ -> dev
- 동일한 로직 2번 사용할 거 같아 일단 custom hook으로 만들 것입니다.
(#222) by @arch-spatula
=> fix(useStopScroll) 모달 open시 백드롭에서 스크롤 방지

Components/Detail/Comment/CommentInput.tsx, Components/Detail/Comment/CommentItem.tsx, Components/Detail/DetailHeader/DetailHeader.tsx
- 좋아요 코멘트 인터렉션 시 카운트 업데이트
- fix/update-like-count-and-comment-count -> dev
- 좋아요와 코멘트를 추가/삭제할 시, 메인 페이지에서 그 수가 업데이트 됩니다.
#199 by @Jeremy-Kr
=> fix: 좋아요 코멘트 인터렉션 시 카운트 업데이트

Components/MyPage/UserInfoContainer/UserInfoContainer.tsx, hooks/query/useUserProfile.ts
- 최초 로드에 유저 프로필이 비어있는 버그 해결
- useUerProfile 문서 업데이트
- feat/ -> dev
- 추가로 useUserInfo custom hook의 문서도 수정했습니다.
(#200) by @arch-spatula
=> fix(UserInfo)최초 로그인시 유저 정보 없음 디버깅

Components/CreatePost/Post/FieldDropDown.tsx, Components/CreatePost/Post/Post.tsx, Components/CreatePost/Post/ProjectInfoDropDown.tsx, Components/Detail/DetailTitle.tsx, Components/Main/MainSection.tsx, Components/Main/SideBar/SideBar.tsx
- 카테고리 수정 -> 풀스택,프론트,백 / 안드로이드,ios, 플러터, RN / AI / Big data 
- feat/re-setting-category -> dev
- 카테고리를 수정하면서 관련된 부분들 수정했습니다. 
- 1. 메인 사이드바에서 toggle (아래 화살표) 버튼을 클릭할 수 없도록 처리했습니다. 
- 2. category 표시 관련 부분에서  sub category만 표시 되도록 했습니다.  ( post, detail, mainpage-postItem )
- 3. 별도로 post의 임시저장 기능을 주석처리했습니다. 
- 4. mainpage에 필터링 기능에 카테고리를 수정했습니다. 
(#219 .) by @yunjunhojj
=> refact: 카테고리 수정

Components/Main/SideBar/SideBar.tsx, styles/global.css, styles/reset.css
- global css 적용 위치 변경
- fix/sidebar-render-bug -> dev
- global css 적용 위치 변경 입니다. 
- reset css의 경우 배포했을 때도 적용되는 것이 확인 되었으니, 해당 부분으로 위치를 이동시켰습니다 
(#171 ) by @yunjunhojj
=> fix: global css 적용 위치 변경

Components/CreatePost/PostEditor.tsx, styles/theme.ts
- FileList타입과 DataTransfer 타입을 지정합니다.
- feat/ -> dev
-
by @arch-spatula
=> hotfix(PostEditor): any 타입 수정

utils/card/findThumbnailInContent.ts
- 썸네일 오류 해결
- fix/thumbnail -> dev
- 썸네일의 url이 변경되며 생긴 문제를 regex를 수정하여 해결합니다.
#246  by @Jeremy-Kr
=> fix: 썸네일 오류 해결

Components/Common/Auth/AuthButton.tsx, Components/Common/Auth/ErrorMessageBox.tsx, Components/Common/Auth/HelperTextBox.tsx, Components/Common/Auth/index.ts, pages/auth/login.tsx, pages/auth/signup.tsx
Auth Page #242
- fix: 디자이너 컨펌에 대한 feedback
- style/auth-page -> dev
- 빠진 font들 처리했습니다.
(#242 ) by @yunjunhojj
=> fix: 디자이너 컨펌에 대한 feedback

Components/MyPage/TabProfile/EditProfileContainer.tsx
- 휴대전화 입력 후 방향키 누르면 문자열에서 숫자 형변환되는 문제를 해결합니다.
- feat/ -> dev
-
(#275) by @arch-spatula
=> fix(EditProfile): 휴대전화 input type number -> tel

Components/Common/Skill/SkillList.tsx, Components/CreatePost/Post/ProjectInfoDropDown.tsx, Components/CreatePost/Post/WithPeople.tsx, Components/CreatePost/PostEditor.tsx
- md editor header 컬러 변경
- fix/Editor-sytle -> dev
- 포스트 페이지의 각 디테일한 디자인 반영
- 에디터의 스타일 수정
(#270) by @hyoloui
=> fix(editor): 에디터 헤더 배경색 변경 및 스타일 부분 수정

Components/Detail/DetailSide/DetailBadgeModal.tsx, Components/Detail/DetailSide/DetailSideBadges.tsx
- feat/ -> dev
- 배지 모달 위치 변경
(#263) by @arch-spatula
=> fix(Detail/SideBadge, BadgeModal): 모달 위치 변경

Components/Detail/DetailTitle.tsx
- feat/ -> dev
-
(#264) by @arch-spatula
=> fix(DetailTitle): Container에 space-between 정상 적용

Components/Main/MainSection.tsx
- main page min height 추가
- feat/ -> dev
- 게시물이 없을 시 푸터가 위로 올라오던 현상을 고칩니다.
#265 by @Jeremy-Kr
=> fix: main page min height 추가

Components/Layouts/NotificationItem.tsx, utils/commons/viewCreateAt.ts
- 알람 시간 추가
- feat/notification-time -> dev
- 알람기능에서 시간을 트래킹합니다.
- viewCreateAt 유틸의 파라미터에 Date타입을 추가합니다.
#266 by @Jeremy-Kr
=> feat: 알람 시간 추가

Components/Layouts/SearchBar.tsx
- 검색시 value가 안들어오던 문제 해결
- fix/search-value -> dev
- 검색시 value가 들어오지 않던 문제를 해결합니다.
#268 by @Jeremy-Kr
=> fix: 검색시 value가 안들어오던 문제 해결

Components/Detail/DetailArticle.tsx, Components/Layouts/Notification.tsx, Components/MyPage/UserInfoContainer/UserInfoContainer.tsx, pages/search.tsx
- Loader 변경
- feat/ -> dev
- 디자이너 요구사항에 의한 변경입니다.
#288 by @Jeremy-Kr
=> fix: Loader 변경

pages/auth/login.tsx
login enter event #269
- enter key 핸들링입니다. 
- feat/ -> dev
- enter key 핸들링입니다.  로그인에만 적용시켰습니다. (회원가입에는 적용 안되어있습니다.)
- 저는 개인적으로 회원가입에는 enter key 핸들링이 필요 없다 생각하는데, 다른 의견있으면 말씀해주세요! 
(#269 ) by @
=> feat: enter key 핸들링

Components/Layouts/Footer.tsx, pages/search.tsx
- Footer 이름 추가
- 인라인 스타일 빼면 밑줄이 생깁니다.
- feat/ -> dev
-
(#289) by @arch-spatula
=> feat(Footer): Footer 스타일 반영

Components/CreatePost/Post/FieldDropDown.tsx, Components/CreatePost/PostEditor.tsx, Components/Detail/DetailContent.tsx, pages/_app.tsx
드롭다운 아이템변경, 전역 테마 dark mode 적용, 불릿포인트 적용
=> hotfix: 드롭다운 아이템변경, 전역 테마 dark mode 적용, 불릿포인트 적용

Components/CreatePost/Post/FieldPicker.tsx, Components/CreatePost/Post/WithPeople.tsx
- post page 버그를 수정합니다.
- fix/post-dropdown -> dev
- 기존은 last 값만 수정 하고 있어 수장합니다.
##AS-IS
##TO-BE
by @hyoloui
=> fix(WithPeople): 함께한 사람들 포지션 버그 수정

Components/CreatePost/Post/Post.tsx, Components/Detail/DetailSide/DetailSide.tsx, Components/Detail/DetailSide/DetailSideBadges.tsx, Components/Detail/DetailSide/DetailSidePeople.tsx, Components/Detail/DetailSide/DetailWith.tsx
- fix: 디테일페이지 github 정보 오류 수정
- fix: 수정 후 무한 loader 현상]
- fix : detail badges 로그인 유도 오류 해결
-  fix/error -> dev
-
#305  by @yunjunhojj
=> Fix/error 깃허브 링크 error 

Components/Common/ConfirmModal.tsx, Components/CreatePost/Post/FieldPicker.tsx, Components/CreatePost/Post/ProjectInfoDropDown.tsx, Components/Detail/Comment/CommentItem.tsx, Components/Detail/DetailArticle.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx, Components/Detail/DetailSide/DetailBadgeModal.tsx, hooks/query/useOutsideClick.ts
- 드롭다운/모달이 켜져있을 때, 외부 화면 클리 시 드롭다운/모달이 종료되는 기능 구현
<br>
- post page: 카테고리 드롭다운
- post page: 참여 포지션 드롭다운
<br>
- detail page: 댓글 드롭다운
<br>
- detail page: 추천뱃지 미니 모달
<br>
- ConfirmModal 
<br>
- feat/backdrop -> dev
- 위의 내용과 동일합니다
#319 by @nno3onn
=> feat: 드롭다운 및 모달 외부 화면 클릭 시 드롭다운 및 모달이 종료되는 기능 구현

Components/Common/ConfirmModal.tsx, Components/CreatePost/Post/FieldPicker.tsx, Components/CreatePost/Post/ProjectInfoDropDown.tsx, Components/Detail/Comment/CommentItem.tsx, Components/Detail/DetailArticle.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx, Components/Detail/DetailSide/DetailBadgeModal.tsx, Components/Layouts/GNB.tsx, Components/Layouts/Notification.tsx, Components/Main/MainSection.tsx, hooks/common/index.ts, hooks/common/useSubscribeRoute.ts, hooks/query/useOutsideClick.ts
- custom hook 추가
- route 변경시 dropdown 초기화
- dropdown 풍선효과 적용
- feat/ -> dev
-
(#318 ) by @arch-spatula
=> fix(GNB, useSubscribeRoute): dropdown 겹치는 문제해결

Components/Common/ProfileImage.tsx, Components/CreatePost/Post/PostTitle.tsx, Components/MyPage/UserInfoContainer/Banner.tsx, Components/MyPage/UserInfoContainer/useUserImage.ts
- 이미지 업로드 시 파일 압축을 적용합니다.
- refactor/compression -> dev
- useUserImage 파일 수정
- PostTitle 파일 수정
(#320) by @hyoloui
=> fix(storage): 이미지 업로드시 파일 압축 전체 적용

Components/CreatePost/Post/ProjectInfoDropDown.tsx
- 데이트 피커 스타일 변경
- fix/date-picker-style -> dev
- 디자이너 요청에 의한 변경입니다.
#330 by @
=> fix: 데이트 피커 스타일 변경

Components/Main/MainSection.tsx
- 그리드에서 플렉스 랩으로 수정하여, 상대적으로 해상도가 낮은 디스플레이에 대응 합니다.
- style/Main-layout -> dev
- 해당하는 styled-component 속성 수정하였습니다.
by @hyoloui
=> style(MainSection): 메인 섹션의 레이아웃을 수정합니다.

Components/Common/ConfirmModal.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx
- 삭제 모달 컬러를 변경하였습니다.
- feat/DeleteModal -> dev
- ConfirmModal 컴포넌트에 type="normal" | "warn" 을 추가하였습니다.
#331  by @nno3onn
=> style: 삭제 모달 컬러 변경

Components/Main/MainSection.tsx, lib/recoil/InfiniteScroll.ts, utils/APIs/supabase/getAllPosts.ts, utils/APIs/supabase/getAllPostsCount.ts, utils/APIs/supabase/getInfinitePosts.ts
- Feat/infinite scroll
- feat/infinite scroll -> dev
- infinite scroll 을 구현 했습니다. 
(#322) by @yunjunhojj
=> Feat/infinite scroll (두배 이벤트 수정해야합니다) 

Components/Main/MainSection.tsx
=> fix: main page justify-content 수정

Components/Common/ConfirmModal.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx, Components/Main/MainSection.tsx
=> fix: 삭제가 안되는 버그를 고칩니다

Components/Common/ConfirmModal.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx, Components/Detail/DetailTitle.tsx, Components/Main/MainSection.tsx
=> hotfix 1.2.0

Components/MyPage/TabProfile/DropDown.tsx, Components/MyPage/TabProfile/EditProfileContainer.tsx, Components/MyPage/TabProfile/ShowProfileContainer.tsx, hooks/query/useUserProfile.ts, lib/recoil/myPageAtoms.ts, types.d.ts
- 출생년도
- 출생년도 선택안함 추가
- 출생년도 타입 숫자형 -> 문자열
- feat/ -> dev
-
(#347) by @arch-spatula
=> fix(DropDown, EditProfile, MyPageAtoms): 출생년도

Components/Layouts/GNB.tsx, hooks/query/useUserProfile.ts, pages/profile/[[...userId]].tsx
- 마이페이지 이동시 다른 페이지 게시물이 불러와짐 해결
- useMemo의 값 생신 기준이 추가되었어야 함
- 의존성 배열에 쿼리파라미터 값 추가로 해결
- feat/ -> dev
-
(#352) by @arch-spatula
=> fix(Profile, useUserProfile, GNB): MyPage Post 갱신

Components/Main/MainSection.tsx, hooks/common/useIntersect.ts, pages/_app.tsx
- Feat/infinite scroll 2배 이벤트를 종료하겠습니다 
- feat/infinite scroll -> dev
- Feat/infinite scroll 2배 이벤트를 종료하겠습니다 
- target (Intersection Observer을 위한 컴포넌트)의 랜더링을 늦췄습니다. 
- 연속 요청하지 않도록 state를 추가했습니다. 
- 혹시 몰라서 Intersection Observer의 로직을 변경했습니다. 
(#353 ) by @yunjunhojj
=> Feat/infinite scroll 2배 이벤트를 종료하겠습니다 

Components/Main/DetailModal.tsx
- 디테일 페이지에서 스크롤바가 적용되지 않는 문제를 해결하였습니다.
- fix/scrollbar-> dev
- 위의 내용과 동일합니다.
#350   by @nno3onnn
=> fix: 디테일 페이지 스크롤바 적용

Components/Common/TopButton.tsx, Components/Detail/DetailArticle.tsx, Components/Main/DetailModal.tsx, Components/Main/MainSection.tsx, pages/index.tsx, public/icons/top-button.svg
- top scroll button 기능을 구현하였습니다.
<br>
- 메인 페이지
<br>
- 디테일 페이지
- feat/ -> dev
- 위의 내용과 동일합니다.
#373  by @nno3onn
=> feat: topButton 기능 구현

Components/Common/PrimaryButton.tsx
컬러, 폰트사이즈, 커서 업데이트
- feat/ -> dev
-
(#371) by @arch-spatula
=> style(PrimaryButton): 컬러, 폰트사이즈, 커서 업데이트

Components/Detail/Comment/Comment.tsx, Components/Detail/Comment/CommentInput.tsx, Components/Detail/Comment/CommentItem.tsx, Components/Detail/DetailArticle.tsx, Components/Detail/DetailBadges.tsx, Components/Detail/DetailBadgesContainer.tsx, Components/Detail/DetailContent.tsx, Components/Detail/DetailHeader/DetailHeader.tsx, Components/Detail/DetailHeader/ShowMoreModal.tsx, Components/Detail/DetailTitle.tsx, Components/Detail/RelatedProject/RelatedProject.tsx, Components/Main/MainSection.tsx
- 디테일페이지 반응형을 해보았습니다.
- style/detail-styeld -> dev
- 디테일페이지 반응형 입니다
- css를 잘 못해서 꼭 preview 확인 부탁드립니다. 
#346  #378 by @yunjunhojj
=> Style/detail styled - 디테일페이지 반응형

Components/Common/TopButton.tsx, Components/Detail/DetailArticle.tsx, Components/Layouts/EmptyContent.tsx, Components/Main/MainSection.tsx
- hotfix/Main -> dev
- 카테고리 length가 0 일 때의 컴포넌트를 추가합니다.
#388 @hyoloui
=> fix(Main): Main Layout을 급히 수정합니다.

Components/Main/MainSection.tsx, pages/_app.tsx, pages/_document.tsx
- 메인 배너가 생기며 드롭다운 위치 버그 픽스
- fix/main-dropdown -> dev
- 드롭다운 위치를 수정합니다.
by @Jeremy-Kr
=> fix: 메인 배너가 생기며 드롭다운 위치 버그 픽스
